Done
Prashant20985/oral-health-indices-monitoring-system-backend pull request #61
Opened 2023-09-11 14:28 UTC by harsh-S21901

2023-09-12 11:17 UTC, Prashant20985 requested changes

2023-09-12 11:17 UTC, Prashant20985 commented on App.API.Test/Controllers/AdminControllerTests/GetActiveUsersTest.cs
Add Tests for GetActiveUsers

2023-09-12 11:17 UTC, Prashant20985 commented on App.API.Test/Controllers/AdminControllerTests/TestableAdminController.cs
> +    {
Add Expose Mediator method

2023-09-13 10:10 UTC, harsh-S21901 commented on App.API.Test/Controllers/AdminControllerTests/GetActiveUsersTest.cs
Resolved

2023-09-13 10:10 UTC, harsh-S21901 commented on App.API.Test/Controllers/AdminControllerTests/TestableAdminController.cs
> +    {
Resolved

2023-09-13 10:10 UTC, Prashant20985 approved these changes

2023-09-13 10:11 UTC, merged